# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
services:
  horusec_postgresql_keycloak:
    network_mode: "host"
    container_name: horusec_postgresql_keycloak
    image: postgres:14
    expose:
      - "5433"
    command: -p 5433
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
        - ./static/auth-keycloak-without-application-admin:/docker-entrypoint-initdb.d
  horusec_keycloak:
    network_mode: "host"
    container_name: horusec_keycloak
    depends_on:
      - "horusec_postgresql_keycloak"
    image: jboss/keycloak:15.1.1
    restart: always
    environment:
      DB_VENDOR: "postgres"
      DB_ADDR: "127.0.0.1"
      DB_PORT: "5433"
      DB_USER: "root"
      DB_PASSWORD: "root"
      KEYCLOAK_USER: "root"
      KEYCLOAK_PASSWORD: "root"
  horusec_rabbit:
    network_mode: "host"
    container_name: horusec_rabbit
    image: rabbitmq:3-management
  horusec_postgresql:
    network_mode: "host"
    container_name: horusec_postgresql
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres/db/data:/var/lib/postgresql/data_e2e_auth_horusec_without_application_admin
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
  horusec-auth:
    network_mode: "host"
    build:
        context: ../../../auth
        dockerfile: ./deployments/dockerfiles/Dockerfile
    depends_on:
      - "horusec_rabbit"
      - "horusec_postgresql"
      - "horusec_keycloak"
      - "horusec_postgresql_keycloak"
    restart: always
    container_name: horusec-auth
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_PORT: "8006"
      HORUSEC_GRPC_PORT: "8007"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_LOG_MODE: "true"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret"
      HORUSEC_KEYCLOAK_BASE_PATH: "http://127.0.0.1:8080"
      HORUSEC_KEYCLOAK_CLIENT_ID: "horusec-private"
      HORUSEC_KEYCLOAK_CLIENT_SECRET: "f00907ba-87b7-441b-aae7-bd4c74de1938"
      HORUSEC_KEYCLOAK_REALM: "master"
      HORUSEC_LDAP_BASE: "dc=wimpi,dc=net"
      HORUSEC_LDAP_HOST: "127.0.0.1"
      HORUSEC_LDAP_PORT: "10389"
      HORUSEC_LDAP_USESSL: "false"
      HORUSEC_LDAP_SKIP_TLS: "true"
      HORUSEC_LDAP_INSECURE_SKIP_VERIFY: "true"
      HORUSEC_LDAP_BINDDN: "uid=admin,ou=system"
      HORUSEC_LDAP_BINDPASSWORD: "secret"
      HORUSEC_LDAP_USERFILTER: "(sAMAccountName=%s)"
      HORUSEC_LDAP_ADMIN_GROUP: "admin"
      HORUSEC_ENABLE_APPLICATION_ADMIN: "false"
      HORUSEC_APPLICATION_ADMIN_DATA: "{}"
      HORUSEC_ENABLE_DEFAULT_USER: "false"
      HORUSEC_DEFAULT_USER_DATA: "{}"
      HORUSEC_AUTH_TYPE: "keycloak"
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
      HORUSEC_DISABLE_EMAILS: "true"
  horusec-core:
    network_mode: "host"
    build:
        context: ../../../core
        dockerfile: ./deployments/dockerfiles/Dockerfile
    depends_on:
      - "horusec_rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
      - "horusec_keycloak"
      - "horusec_postgresql_keycloak"
    restart: always
    container_name: horusec-core
    environment:
      HORUSEC_PORT: "8003"
      HORUSEC_DISABLED_BROKER: "true"
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_LOG_MODE: "false"
      HORUSEC_GRPC_AUTH_URL: "127.0.0.1:8007"
  horusec-analytic:
    network_mode: "host"
    build:
        context: ../../../analytic
        dockerfile: ./deployments/dockerfiles/Dockerfile
    depends_on:
      - "horusec_rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
      - "horusec_keycloak"
      - "horusec_postgresql_keycloak"
    restart: always
    container_name: horusec-analytic
    environment:
      HORUSEC_PORT: "8005"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_analytic_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_LOG_MODE: "false"
      HORUSEC_GRPC_AUTH_URL: "127.0.0.1:8007"
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
  horusec-api:
    network_mode: "host"
    build:
        context: ../../../api
        dockerfile: ./deployments/dockerfiles/Dockerfile
    depends_on:
      - "horusec_rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
      - "horusec_keycloak"
      - "horusec_postgresql_keycloak"
    restart: always
    container_name: horusec-api
    environment:
      HORUSEC_PORT: "8000"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_LOG_MODE: "false"
      HORUSEC_GRPC_AUTH_URL: "127.0.0.1:8007"
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
  horusec-vulnerability:
    network_mode: "host"
    build:
        context: ../../../vulnerability
        dockerfile: ./deployments/dockerfiles/Dockerfile
    depends_on:
      - "horusec_rabbit"
      - "horusec_postgresql"
      - "horusec_keycloak"
      - "horusec_postgresql_keycloak"
    restart: always
    container_name: horusec-vulnerability
    environment:
      HORUSEC_PORT: "8001"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_LOG_MODE: "false"
      HORUSEC_GRPC_AUTH_URL: "127.0.0.1:8007"
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
  horusec-webhook:
    network_mode: "host"
    build:
        context: ../../../webhook
        dockerfile: ./deployments/dockerfiles/Dockerfile
    depends_on:
      - "horusec_rabbit"
      - "horusec_postgresql"
      - "horusec_keycloak"
      - "horusec_postgresql_keycloak"
    restart: always
    container_name: horusec-webhook
    environment:
     HORUSEC_PORT: "8004"
     HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
     HORUSEC_DATABASE_SQL_LOG_MODE: "false"
     HORUSEC_GRPC_AUTH_URL: "127.0.0.1:8007"
     HORUSEC_BROKER_HOST: "127.0.0.1"
     HORUSEC_BROKER_PORT: "5672"
     HORUSEC_BROKER_USERNAME: "guest"
     HORUSEC_BROKER_PASSWORD: "guest"
  horusec-manager:
    build:
        context: ../../../manager
        dockerfile: ./deployments/dockerfiles/Dockerfile
    ports:
      - "8043:8080"
    restart: always
    container_name: horusec-manager
    environment:
      HORUSEC_ENDPOINT_API: ${HORUSEC_ENDPOINT_API}
      HORUSEC_ENDPOINT_ANALYTIC: ${HORUSEC_ENDPOINT_ANALYTIC}
      HORUSEC_ENDPOINT_CORE: ${HORUSEC_ENDPOINT_CORE}
      HORUSEC_ENDPOINT_WEBHOOK: ${HORUSEC_ENDPOINT_WEBHOOK}
      HORUSEC_ENDPOINT_AUTH: ${HORUSEC_ENDPOINT_AUTH}
      HORUSEC_ENDPOINT_VULNERABILITY: ${HORUSEC_ENDPOINT_VULNERABILITY}
      REACT_APP_HORUSEC_ENDPOINT_API: ${HORUSEC_ENDPOINT_API}
      REACT_APP_HORUSEC_ENDPOINT_ANALYTIC: ${HORUSEC_ENDPOINT_ANALYTIC}
      REACT_APP_HORUSEC_ENDPOINT_CORE: ${HORUSEC_ENDPOINT_CORE}
      REACT_APP_HORUSEC_ENDPOINT_WEBHOOK: ${HORUSEC_ENDPOINT_WEBHOOK}
      REACT_APP_HORUSEC_ENDPOINT_AUTH: ${HORUSEC_ENDPOINT_AUTH}
      REACT_APP_HORUSEC_ENDPOINT_VULNERABILITY: ${HORUSEC_ENDPOINT_VULNERABILITY}
      REACT_APP_KEYCLOAK_BASE_PATH: "http:\\/\\/127.0.0.1:8080\\/auth"
      REACT_APP_KEYCLOAK_CLIENT_ID: "horusec-public"
      REACT_APP_KEYCLOAK_REALM: "master"
      REACT_APP_MICROFRONTEND_PUBLIC_PATH: ${REACT_APP_MICROFRONTEND_PUBLIC_PATH}
      REACT_APP_HORUSEC_MANAGER_THEME: ${REACT_APP_HORUSEC_MANAGER_THEME}
