definitions:
  dashboard.Response:
    properties:
      totalAuthors:
        type: integer
      totalRepositories:
        type: integer
      vulnerabilitiesByAuthor:
        items:
          $ref: '#/definitions/dashboard.ResponseByAuthor'
        type: array
      vulnerabilitiesByLanguage:
        items:
          $ref: '#/definitions/dashboard.ResponseByLanguage'
        type: array
      vulnerabilitiesByRepository:
        items:
          $ref: '#/definitions/dashboard.ResponseByRepository'
        type: array
      vulnerabilityBySeverity:
        $ref: '#/definitions/dashboard.ResponseSeverity'
      vulnerabilityByTime:
        items:
          $ref: '#/definitions/dashboard.ResponseByTime'
        type: array
    type: object
  dashboard.ResponseByAuthor:
    properties:
      author:
        type: string
      critical:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      high:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      info:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      low:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      medium:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      unknown:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
    type: object
  dashboard.ResponseByLanguage:
    properties:
      critical:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      high:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      info:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      language:
        type: string
      low:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      medium:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      unknown:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
    type: object
  dashboard.ResponseByRepository:
    properties:
      critical:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      high:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      info:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      low:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      medium:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      repositoryName:
        type: string
      unknown:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
    type: object
  dashboard.ResponseByTime:
    properties:
      critical:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      high:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      info:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      low:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      medium:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      time:
        type: string
      unknown:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
    type: object
  dashboard.ResponseSeverity:
    properties:
      critical:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      high:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      info:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      low:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      medium:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
      unknown:
        $ref: '#/definitions/dashboard.ResponseSeverityContAndTypes'
    type: object
  dashboard.ResponseSeverityContAndTypes:
    properties:
      count:
        type: integer
      types:
        $ref: '#/definitions/dashboard.ResponseVulnTypes'
    type: object
  dashboard.ResponseVulnTypes:
    properties:
      corrected:
        type: integer
      falsePositive:
        type: integer
      riskAccepted:
        type: integer
      unknown:
        type: integer
      vulnerability:
        type: integer
    type: object
  entities.Response:
    properties:
      code:
        type: integer
      content:
        type: object
      status:
        type: string
    type: object
info:
  contact:
    email: horusec@zup.com.br
    name: Horusec
    url: https://github.com/ZupIT/horusec-platform
  description: Service responsible for managing vulnerabilities.
  termsOfService: http://swagger.io/terms/
  title: Horusec-Analytic
paths:
  /analytic/dashboard/{workspaceID}/dashboard-charts:
    get:
      consumes:
      - application/json
      description: Get all charts of dashboard screen
      operationId: get-total-developers-workspace
      parameters:
      - description: workspaceID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      - description: repositoryID query string
        in: query
        name: repositoryID
        type: string
      - description: initialDate query string
        in: query
        name: initialDate
        type: string
      - description: finalDate query string
        in: query
        name: finalDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entities.Response'
            - properties:
                content:
                  $ref: '#/definitions/dashboard.Response'
              type: object
        "400":
          description: BAD REQUEST
          schema:
            allOf:
            - $ref: '#/definitions/entities.Response'
            - properties:
                content:
                  type: string
              type: object
        "500":
          description: INTERNAL SERVER ERROR
          schema:
            allOf:
            - $ref: '#/definitions/entities.Response'
            - properties:
                content:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      tags:
      - DashboardByWorkspace
  /analytic/health:
    get:
      consumes:
      - application/json
      description: Check if Health of service it's OK!
      operationId: health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/entities.Response'
            - properties:
                content:
                  type: string
              type: object
        "500":
          description: INTERNAL SERVER ERROR
          schema:
            allOf:
            - $ref: '#/definitions/entities.Response'
            - properties:
                content:
                  type: string
              type: object
      tags:
      - Health
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Horusec-Authorization
    type: apiKey
swagger: "2.0"
