definitions:
  authentication.LoginCredentials:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  entities.Response:
    properties:
      code:
        type: integer
      content:
        type: object
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/authenticate/login:
    post:
      consumes:
      - application/json
      description: Login in into a horusec account
      operationId: login
      parameters:
      - description: login data
        in: body
        name: Credentials
        required: true
        schema:
          $ref: '#/definitions/authentication.LoginCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Authenticate
swagger: "2.0"
