# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.components.core.pod.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: horusec-core
  name: {{ .Values.components.core.name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "deployment.apiVersion" . }}
    kind: Deployment
    name: {{ .Values.components.core.name }}
  minReplicas: {{ .Values.components.core.pod.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.components.core.pod.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.components.core.pod.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.components.core.pod.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.components.core.pod.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.components.core.pod.autoscaling.targetMemory }}
    {{- end }}
{{- end }}
