{{- if .Values.components.messages.enabled }}
apiVersion: {{ include "deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: horusec-messages
  name: {{ .Values.components.messages.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.components.messages.pod.autoscaling.enabled }}
  replicas: {{ .Values.components.messages.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: horusec-messages
  template:
    metadata:
      labels:
        app: horusec-messages
    spec:
      {{- include "messages.imagePullSecrets" . | nindent 6 -}}
      containers:
        - env:
          - name: HORUSEC_PORT
            value: {{ .Values.components.messages.port.http | quote }}
          - name: HORUSEC_BROKER_HOST
            value: {{ required "A valid global.broker.host is required!" .Values.global.broker.host }}
          - name: HORUSEC_BROKER_PORT
            value: {{ .Values.global.broker.port | quote }}
          - name: HORUSEC_BROKER_USERNAME
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.broker.user.secretKeyRef | nindent 16 }}
          - name: HORUSEC_BROKER_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.broker.password.secretKeyRef | nindent 16 }}
          - name: HORUSEC_SMTP_ADDRESS
            value: {{ .Values.components.messages.mailServer.host }}
          - name: HORUSEC_SMTP_HOST
            value: {{ .Values.components.messages.mailServer.host }}
          - name: HORUSEC_SMTP_PORT
            value: {{ .Values.components.messages.mailServer.port | quote }}
          - name: HORUSEC_EMAIL_FROM
            value: {{ .Values.components.messages.mailServer.from | quote }}
          - name: HORUSEC_SMTP_USERNAME
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.components.messages.mailServer.user.secretKeyRef | nindent 16 }}
          - name: HORUSEC_SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.components.messages.mailServer.password.secretKeyRef | nindent 16 }}
          {{- if .Values.components.messages.extraEnv }}
          # Extra environment variables
          {{- toYaml .Values.components.messages.extraEnv | nindent 12 }}
          {{- end }}
          image: "{{ template "messages.image" . }}"
          imagePullPolicy: {{ .Values.components.messages.container.image.pullPolicy | quote }}
          name: horusec-messages
          ports:
          {{- range $key, $value := .Values.components.messages.port }}
            - containerPort: {{ $value }}
              name: {{ $key }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /messages/health
              port: http
              scheme: HTTP
          {{- if .Values.components.messages.container.livenessProbe }}
            failureThreshold: {{ .Values.components.messages.container.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.components.messages.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.components.messages.container.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.components.messages.container.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.components.messages.container.livenessProbe.timeoutSeconds }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /messages/health
              port: http
              scheme: HTTP
          {{- if .Values.components.messages.container.readinessProbe }}
            failureThreshold: {{ .Values.components.messages.container.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.components.messages.container.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.components.messages.container.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.components.messages.container.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.components.messages.container.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.components.messages.container.resources }}
          resources: {{- toYaml .Values.components.messages.container.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.components.messages.container.securityContext.enabled }}
          securityContext: {{- omit .Values.components.messages.container.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
      {{- if .Values.components.messages.pod.securityContext.enabled }}
      securityContext: {{- omit .Values.components.messages.pod.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: messages
      terminationGracePeriodSeconds: 30
{{- end }}