# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: {{ include "deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: horusec-vulnerability
  name: {{ .Values.components.vulnerability.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.components.vulnerability.pod.autoscaling.enabled }}
  replicas: {{ .Values.components.vulnerability.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: horusec-vulnerability
  template:
    metadata:
      labels:
        app: horusec-vulnerability
    spec:
      {{- include "vulnerability.imagePullSecrets" . | nindent 6 -}}
      containers:
        - env:
          - name: HORUSEC_PORT
            value: {{ .Values.components.vulnerability.port.http | quote }}
          - name: HORUSEC_SWAGGER_HOST
            value: 0.0.0.0
          - name: HORUSEC_DATABASE_SQL_LOG_MODE
            value: {{ .Values.global.database.logMode | quote }}
          - name: HORUSEC_GRPC_AUTH_URL
            value: "auth.{{- .Release.Namespace -}}.svc.cluster.local:{{- .Values.components.auth.port.grpc }}"
          - name: HORUSEC_GRPC_USE_CERTS
            value: "false"
          - name: HORUSEC_BROKER_HOST
            value: {{ required "A valid global.broker.host is required!" .Values.global.broker.host }}
          - name: HORUSEC_BROKER_PORT
            value: {{ .Values.global.broker.port | quote }}
          - name: HORUSEC_BROKER_USERNAME
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.broker.user.secretKeyRef | nindent 16 }}
          - name: HORUSEC_BROKER_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.broker.password.secretKeyRef | nindent 16 }}
          - name: HORUSEC_DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.database.user.secretKeyRef | nindent 16 }}
          - name: HORUSEC_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.database.password.secretKeyRef | nindent 16 }}
          - name: HORUSEC_DATABASE_SQL_URI
            value: {{ include "global.database.uri" . }}
          {{- if .Values.components.vulnerability.extraEnv }}
          # Extra environment variables
          {{- toYaml .Values.components.vulnerability.extraEnv | nindent 12 }}
          {{- end }}
          image: "{{ template "vulnerability.image" . }}"
          imagePullPolicy: {{ .Values.components.vulnerability.container.image.pullPolicy | quote }}
          name: horusec-vulnerability
          ports:
          {{- range $key, $value := .Values.components.vulnerability.port }}
            - containerPort: {{ $value }}
              name: {{ $key }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /vulnerability/health
              port: http
              scheme: HTTP
          {{- if .Values.components.vulnerability.container.livenessProbe }}
            failureThreshold: {{ .Values.components.vulnerability.container.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.components.vulnerability.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.components.vulnerability.container.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.components.vulnerability.container.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.components.vulnerability.container.livenessProbe.timeoutSeconds }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /vulnerability/health
              port: http
              scheme: HTTP
          {{- if .Values.components.vulnerability.container.readinessProbe }}
            failureThreshold: {{ .Values.components.vulnerability.container.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.components.vulnerability.container.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.components.vulnerability.container.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.components.vulnerability.container.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.components.vulnerability.container.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.components.vulnerability.container.resources }}
          resources: {{- toYaml .Values.components.vulnerability.container.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.components.vulnerability.container.securityContext.enabled }}
          securityContext: {{- omit .Values.components.vulnerability.container.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
      {{- if .Values.components.vulnerability.pod.securityContext.enabled }}
      securityContext: {{- omit .Values.components.vulnerability.pod.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: vulnerability
      terminationGracePeriodSeconds: 30
