BEGIN;

CREATE TABLE IF NOT EXISTS "vulnerabilities_by_author"
(
    "vulnerability_id" UUID NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "author" VARCHAR(500) NOT NULL,
    "active" BOOLEAN NOT NULL,
    "workspace_id" UUID NOT NULL,
    "repository_id" UUID NOT NULL,
    "critical_vulnerability" INT NOT NULL,
    "critical_false_positive" INT NOT NULL,
    "critical_risk_accepted" INT NOT NULL,
    "critical_corrected" INT NOT NULL,
    "high_vulnerability" INT NOT NULL,
    "high_false_positive" INT NOT NULL,
    "high_risk_accepted" INT NOT NULL,
    "high_corrected" INT NOT NULL,
    "medium_vulnerability" INT NOT NULL,
    "medium_false_positive" INT NOT NULL,
    "medium_risk_accepted" INT NOT NULL,
    "medium_corrected" INT NOT NULL,
    "low_vulnerability" INT NOT NULL,
    "low_false_positive" INT NOT NULL,
    "low_risk_accepted" INT NOT NULL,
    "low_corrected" INT NOT NULL,
    "info_vulnerability" INT NOT NULL,
    "info_false_positive" INT NOT NULL,
    "info_risk_accepted" INT NOT NULL,
    "info_corrected" INT NOT NULL,
    "unknown_vulnerability" INT NOT NULL,
    "unknown_false_positive" INT NOT NULL,
    "unknown_risk_accepted" INT NOT NULL,
    "unknown_corrected" INT NOT NULL,
    PRIMARY KEY (vulnerability_id)
);

CREATE TABLE IF NOT EXISTS "vulnerabilities_by_language"
(
    "vulnerability_id" UUID NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "language" VARCHAR(255) NOT NULL,
    "active" BOOLEAN NOT NULL,
    "workspace_id" UUID NOT NULL,
    "repository_id" UUID NOT NULL,
    "critical_vulnerability" INT NOT NULL,
    "critical_false_positive" INT NOT NULL,
    "critical_risk_accepted" INT NOT NULL,
    "critical_corrected" INT NOT NULL,
    "high_vulnerability" INT NOT NULL,
    "high_false_positive" INT NOT NULL,
    "high_risk_accepted" INT NOT NULL,
    "high_corrected" INT NOT NULL,
    "medium_vulnerability" INT NOT NULL,
    "medium_false_positive" INT NOT NULL,
    "medium_risk_accepted" INT NOT NULL,
    "medium_corrected" INT NOT NULL,
    "low_vulnerability" INT NOT NULL,
    "low_false_positive" INT NOT NULL,
    "low_risk_accepted" INT NOT NULL,
    "low_corrected" INT NOT NULL,
    "info_vulnerability" INT NOT NULL,
    "info_false_positive" INT NOT NULL,
    "info_risk_accepted" INT NOT NULL,
    "info_corrected" INT NOT NULL,
    "unknown_vulnerability" INT NOT NULL,
    "unknown_false_positive" INT NOT NULL,
    "unknown_risk_accepted" INT NOT NULL,
    "unknown_corrected" INT NOT NULL,
    PRIMARY KEY (vulnerability_id)
);

CREATE TABLE IF NOT EXISTS "vulnerabilities_by_repository"
(
    "vulnerability_id" UUID NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "repository_name" VARCHAR(255) NOT NULL,
    "active" BOOLEAN NOT NULL,
    "workspace_id" UUID NOT NULL,
    "repository_id" UUID NOT NULL,
    "critical_vulnerability" INT NOT NULL,
    "critical_false_positive" INT NOT NULL,
    "critical_risk_accepted" INT NOT NULL,
    "critical_corrected" INT NOT NULL,
    "high_vulnerability" INT NOT NULL,
    "high_false_positive" INT NOT NULL,
    "high_risk_accepted" INT NOT NULL,
    "high_corrected" INT NOT NULL,
    "medium_vulnerability" INT NOT NULL,
    "medium_false_positive" INT NOT NULL,
    "medium_risk_accepted" INT NOT NULL,
    "medium_corrected" INT NOT NULL,
    "low_vulnerability" INT NOT NULL,
    "low_false_positive" INT NOT NULL,
    "low_risk_accepted" INT NOT NULL,
    "low_corrected" INT NOT NULL,
    "info_vulnerability" INT NOT NULL,
    "info_false_positive" INT NOT NULL,
    "info_risk_accepted" INT NOT NULL,
    "info_corrected" INT NOT NULL,
    "unknown_vulnerability" INT NOT NULL,
    "unknown_false_positive" INT NOT NULL,
    "unknown_risk_accepted" INT NOT NULL,
    "unknown_corrected" INT NOT NULL,
    PRIMARY KEY (vulnerability_id)
);

CREATE TABLE IF NOT EXISTS "vulnerabilities_by_time"
(
    "vulnerability_id" UUID NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "active" BOOLEAN NOT NULL,
    "workspace_id" UUID NOT NULL,
    "repository_id" UUID NOT NULL,
    "critical_vulnerability" INT NOT NULL,
    "critical_false_positive" INT NOT NULL,
    "critical_risk_accepted" INT NOT NULL,
    "critical_corrected" INT NOT NULL,
    "high_vulnerability" INT NOT NULL,
    "high_false_positive" INT NOT NULL,
    "high_risk_accepted" INT NOT NULL,
    "high_corrected" INT NOT NULL,
    "medium_vulnerability" INT NOT NULL,
    "medium_false_positive" INT NOT NULL,
    "medium_risk_accepted" INT NOT NULL,
    "medium_corrected" INT NOT NULL,
    "low_vulnerability" INT NOT NULL,
    "low_false_positive" INT NOT NULL,
    "low_risk_accepted" INT NOT NULL,
    "low_corrected" INT NOT NULL,
    "info_vulnerability" INT NOT NULL,
    "info_false_positive" INT NOT NULL,
    "info_risk_accepted" INT NOT NULL,
    "info_corrected" INT NOT NULL,
    "unknown_vulnerability" INT NOT NULL,
    "unknown_false_positive" INT NOT NULL,
    "unknown_risk_accepted" INT NOT NULL,
    "unknown_corrected" INT NOT NULL,
    PRIMARY KEY (vulnerability_id)
);

COMMIT;
