apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade,post-rollback"
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  template:
    metadata:
      name: migration
    spec:
      restartPolicy: Never
      containers:
        - name: horusec-database-migration
          image: "horuszup/horusec-migration:latest"
          command: [ "migrate.sh" ]
          env:
            - name: HORUSEC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                {{- toYaml .Values.components.analytic.database.user.secretKeyRef | nindent 18 }}
            - name: HORUSEC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- toYaml .Values.components.analytic.database.password.secretKeyRef | nindent 18 }}
            - name: MIGRATION_NAME
              value: "analytic"
            - name: HORUSEC_DATABASE_SQL_URI
              value: "postgresql://$(HORUSEC_DATABASE_USERNAME):$(HORUSEC_DATABASE_PASSWORD)@{{- include "database.address" . -}}{{- if not .Values.global.database.sslMode -}}?sslmode=disable{{- end -}}"
