apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-platform-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  template:
    metadata:
      name: migration
    spec:
      restartPolicy: Never
      containers:
        - name: horusec-database-migration
          image: "{{ template "global.database.migration.image" . }}"
          command: [ "migrate.sh" ]
          env:
            - name: HORUSEC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                {{- toYaml .Values.global.database.user.secretKeyRef | nindent 18 }}
            - name: HORUSEC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- toYaml .Values.global.database.password.secretKeyRef | nindent 18 }}
            - name: MIGRATION_NAME
              value: "platform"
            - name: HORUSEC_DATABASE_SQL_URI
              value: {{ include "global.database.uri" . }}
