// Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	account "github.com/ZupIT/horusec-platform/auth/internal/entities/account"

	mock "github.com/stretchr/testify/mock"
)

// AdminAccount is an autogenerated mock type for the AdminAccount type
type AdminAccount struct {
	mock.Mock
}

// CreateOrUpdate provides a mock function with given fields: _a0
func (_m *AdminAccount) CreateOrUpdate(_a0 *account.Account) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
