// Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	"github.com/ZupIT/horusec-devkit/pkg/services/database"
	"github.com/ZupIT/horusec-devkit/pkg/services/database/response"

	"github.com/stretchr/testify/mock"
)

// IDatabaseWrite is an autogenerated mock type for the IDatabaseWrite type
type IDatabaseWrite struct {
	mock.Mock
}

// CommitTransaction provides a mock function with given fields:
func (_m *IDatabaseWrite) CommitTransaction() response.IResponse {
	ret := _m.Called()

	var r0 response.IResponse
	if rf, ok := ret.Get(0).(func() response.IResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.IResponse)
		}
	}

	return r0
}

// Create provides a mock function with given fields: entityPointer, table
func (_m *IDatabaseWrite) Create(entityPointer interface{}, table string) response.IResponse {
	ret := _m.Called(entityPointer, table)

	var r0 response.IResponse
	if rf, ok := ret.Get(0).(func(interface{}, string) response.IResponse); ok {
		r0 = rf(entityPointer, table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.IResponse)
		}
	}

	return r0
}

// CreateOrUpdate provides a mock function with given fields: entityPointer, where, table
func (_m *IDatabaseWrite) CreateOrUpdate(entityPointer interface{}, where map[string]interface{}, table string) response.IResponse {
	ret := _m.Called(entityPointer, where, table)

	var r0 response.IResponse
	if rf, ok := ret.Get(0).(func(interface{}, map[string]interface{}, string) response.IResponse); ok {
		r0 = rf(entityPointer, where, table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.IResponse)
		}
	}

	return r0
}

// Delete provides a mock function with given fields: where, table
func (_m *IDatabaseWrite) Delete(where map[string]interface{}, table string) response.IResponse {
	ret := _m.Called(where, table)

	var r0 response.IResponse
	if rf, ok := ret.Get(0).(func(map[string]interface{}, string) response.IResponse); ok {
		r0 = rf(where, table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.IResponse)
		}
	}

	return r0
}

// IsAvailable provides a mock function with given fields:
func (_m *IDatabaseWrite) IsAvailable() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RollbackTransaction provides a mock function with given fields:
func (_m *IDatabaseWrite) RollbackTransaction() response.IResponse {
	ret := _m.Called()

	var r0 response.IResponse
	if rf, ok := ret.Get(0).(func() response.IResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.IResponse)
		}
	}

	return r0
}

// StartTransaction provides a mock function with given fields:
func (_m *IDatabaseWrite) StartTransaction() database.IDatabaseWrite {
	ret := _m.Called()

	var r0 database.IDatabaseWrite
	if rf, ok := ret.Get(0).(func() database.IDatabaseWrite); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.IDatabaseWrite)
		}
	}

	return r0
}

// Update provides a mock function with given fields: entityPointer, where, table
func (_m *IDatabaseWrite) Update(entityPointer interface{}, where map[string]interface{}, table string) response.IResponse {
	ret := _m.Called(entityPointer, where, table)

	var r0 response.IResponse
	if rf, ok := ret.Get(0).(func(interface{}, map[string]interface{}, string) response.IResponse); ok {
		r0 = rf(entityPointer, where, table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.IResponse)
		}
	}

	return r0
}
