# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-v1-2-v2"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-v1-2-v2-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-v1-2-v2"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-v1-2-v2-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: horusec-analytic-v1-2-v2
        image: "horuszup/horusec-analytic:v2.14.0"
        command: "./horusec-analytic-v1-2-v2-migrate $HORUSEC_DATABASE_HORUSEC_SQL_URI"
        env:          
          - name: MIGRATION_NAME
            value: "platform"
        {{- range .Values.env }}
          - name: {{ .name }}
            value: "{{ .value }}" 
        {{- end }}
        {{- range .Values.envFromSecret }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .key }}
                key: {{ .key }}
        {{- end }}
