apiVersion: v1
kind: Service
metadata:
  labels:
    app: horusec-manager
  name: {{ .Values.components.manager.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- range $key, $value := .Values.components.manager.port }}
    - name: {{ $key }}
      port: {{ $value }}
      protocol: TCP
      targetPort: {{ $key }}
  {{- end }}
  selector:
    app: horusec-manager
  type: ClusterIP
