definitions:
  entities.Response:
    properties:
      code:
        type: integer
      content:
        type: object
      status:
        type: string
    type: object
  repository.Data:
    properties:
      authzAdmin:
        items:
          type: string
        type: array
      authzMember:
        items:
          type: string
        type: array
      authzSupervisor:
        items:
          type: string
        type: array
      description:
        type: string
      name:
        type: string
    type: object
  role.Data:
    properties:
      role:
        type: string
    type: object
  role.InviteUserData:
    properties:
      accountID:
        type: string
      email:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  workspace.Data:
    properties:
      authzAdmin:
        items:
          type: string
        type: array
      authzMember:
        items:
          type: string
        type: array
      description:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: horusec@zup.com.br
    name: Horusec
    url: https://github.com/ZupIT/horusec-platform
  description: Service responsible for workspace, repositories and token operations.
  termsOfService: http://swagger.io/terms/
  title: Horusec-Core
paths:
  /core/workspaces:
    get:
      consumes:
      - application/json
      description: List all workspaces of an account
      operationId: list-workspace
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Workspace
    post:
      consumes:
      - application/json
      description: Create a new workspace
      operationId: create-workspace
      parameters:
      - description: create workspace data
        in: body
        name: Workspace
        required: true
        schema:
          $ref: '#/definitions/workspace.Data'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Workspace
  /core/workspaces/{workspaceID}:
    delete:
      consumes:
      - application/json
      description: Delete a workspace by id
      operationId: delete-workspace
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Workspace
    get:
      consumes:
      - application/json
      description: Search for a existing workspace by id
      operationId: get-workspace
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Workspace
    patch:
      consumes:
      - application/json
      description: Updates a existing workspace by id
      operationId: update-workspace
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      - description: update workspace data
        in: body
        name: Workspace
        required: true
        schema:
          $ref: '#/definitions/workspace.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Workspace
  /core/workspaces/{workspaceID}/repositories:
    post:
      consumes:
      - application/json
      description: Create a new repository
      operationId: create-repository
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      - description: create repository data
        in: body
        name: Repository
        required: true
        schema:
          $ref: '#/definitions/repository.Data'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Repository
  /core/workspaces/{workspaceID}/repositories/{repositoryID}:
    get:
      consumes:
      - application/json
      description: Search for a existing repository by id
      operationId: get-repository
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      - description: ID of the repository
        in: path
        name: repositoryID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Repository
    patch:
      consumes:
      - application/json
      description: Updates a existing repository by id
      operationId: update-repository
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      - description: ID of the repository
        in: path
        name: repositoryID
        required: true
        type: string
      - description: update repository data
        in: body
        name: Repository
        required: true
        schema:
          $ref: '#/definitions/repository.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Repository
  /core/workspaces/{workspaceID}/roles:
    get:
      consumes:
      - application/json
      description: Get all users of a workspace
      operationId: get-users
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Workspace
    post:
      consumes:
      - application/json
      description: Invite a user to a workspace
      operationId: invite-user
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      - description: update role of a account in a specific workspace
        in: body
        name: Workspace
        required: true
        schema:
          $ref: '#/definitions/role.InviteUserData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Workspace
  /core/workspaces/{workspaceID}/roles/{accountID}:
    delete:
      consumes:
      - application/json
      description: Remove a user from a workspace
      operationId: remove-user
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      - description: ID of the account
        in: path
        name: accountID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Workspace
    patch:
      consumes:
      - application/json
      description: Update an account role of a workspace
      operationId: workspace-role
      parameters:
      - description: ID of the workspace
        in: path
        name: workspaceID
        required: true
        type: string
      - description: ID of the account
        in: path
        name: accountID
        required: true
        type: string
      - description: update role of a account in a specific workspace
        in: body
        name: Workspace
        required: true
        schema:
          $ref: '#/definitions/role.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Response'
      security:
      - ApiKeyAuth: []
      tags:
      - Workspace
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Horusec-Authorization
    type: apiKey
swagger: "2.0"
