name: Core
on:
  push:
    paths: [
        "auth/**",
        "**/workflows/core-pipeline.yml",
    ]
jobs:
  lint-coverage-build-security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: lint
        run: make lint
      - name: coverage
        run: make coverage
      - name: build
        run: make build
      - name: security
        run: make security
