name: Manager
on:
  push:
    paths: ["manager/**", "**/workflows/manager-pipeline.yml"]
jobs:
  lint-coverage-build-security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: manager
    steps:
      - name: Set up nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12"
        id: node
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      # - name: Install dependencies
      #   run: npm install
      # - name: Security
      #   run: make security
      # - name: Lint
      #   run: npm run lint
      # - name: Build
      #   run: npm run build
      - name: Test
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          working-directory: manager
      - name: Archive cypress tests artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-tests-results
          path: |
            /cypress/screenshots
            /cypress/videos
