# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Manager
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint-coverage-build-security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: manager
    steps:
      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"
        id: node
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        uses: cypress-io/github-action@v2
        with:
          working-directory: manager
          browser: chrome
          install-command: yarn
          build: yarn build
          start: npx serve -s build -l 3000
          wait-on: 'http://localhost:3000'
      - name: Upload cypress videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: manager/cypress/videos
      - name: security
        env:
          HORUSEC_CLI_REPOSITORY_AUTHORIZATION: ${{ secrets.HORUSEC_CLI_REPOSITORY_AUTHORIZATION }}
          HORUSEC_CLI_HORUSEC_API_URI: ${{ secrets.HORUSEC_CLI_HORUSEC_API_URI }}
          REPOSITORY_OWNER: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p . -e=$(if [ "$REPOSITORY_OWNER" == "ZupIT/horusec" ]; then echo "true"; else echo "false"; fi) -G -n="Horusec/Platform-Manager" --show-vulnerabilities-types="Vulnerability, Risk Accepted"
