name: Manager
on:
  push:
    paths: ["manager/**", "**/workflows/manager-pipeline.yml"]
jobs:
  lint-coverage-build-security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: manager
    steps:
      - name: Set up nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12"
        id: node
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Security
        run: make security
      - name: Lint
        run: npm run lint
      - name: Test
        uses: cypress-io/github-action@v2
        with:
          working-directory: manager
          browser: chrome
          build: npm run build
          start: npx serve -s build -l 3000
          wait-on: 'http://localhost:3000'
      - name: Upload cypress videos
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: manager/cypress/videos

