# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
services:
#  ldap-service:
#    container_name: ldap-service
#    image: dwimberger/ldap-ad-it
#    ports:
#      - "10389:10389"
#  postgresql_keycloak:
#    container_name: postgresql_keycloak
#    image: postgres:12
#    ports:
#      - "5433:5433"
#    expose:
#      - "5433"
#    command: -p 5433
#    environment:
#      POSTGRES_PASSWORD: root # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
#      POSTGRES_USER: root # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
#      POSTGRES_DB: keycloak
#  keycloak:
#    depends_on:
#      - "postgresql_keycloak"
#    container_name: keycloak
#    image: jboss/keycloak
#    ports:
#      - "8080:8080"
#    environment:
#      DB_VENDOR: "postgres"
#      DB_ADDR: postgresql_keycloak
#      DB_PORT: "5433"
#      DB_USER: "root" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
#      DB_PASSWORD: "root" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
#      KEYCLOAK_USER: "keycloak" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
#      KEYCLOAK_PASSWORD: "keycloak" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  horusec_postgresql:
    container_name: horusec_postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      POSTGRES_USER: root # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres/db/data:/var/lib/postgresql/data
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
  horusec-messages:
    image: horuszup/horusec-messages:v2.17.2
    ports:
      - "8002:8002"
    depends_on:
      - "rabbit"
    restart: always
    container_name: horusec-messages
    environment:
      HORUSEC_PORT: "8002"
      HORUSEC_BROKER_HOST: "rabbit"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_SMTP_ADDRESS: "smtp.mailtrap.io"
      HORUSEC_SMTP_USERNAME: ${HORUSEC_SMTP_USERNAME} # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_SMTP_PASSWORD: ${HORUSEC_SMTP_PASSWORD} # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_SMTP_HOST: "smtp.mailtrap.io"
      HORUSEC_SMTP_PORT: "2525"
      HORUSEC_EMAIL_FROM: "horusec@zup.com.br"
  horusec-auth:
    image: horuszup/horusec-auth:v2.17.2
    ports:
      - "8006:8006"
      - "8007:8007"
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
    restart: always
    container_name: horusec-auth
    environment:
      HORUSEC_PORT: "8006"
      HORUSEC_GRPC_PORT: "8007"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@horusec_postgresql:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "false"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_KEYCLOAK_BASE_PATH: ${HORUSEC_KEYCLOAK_BASE_PATH}
      HORUSEC_KEYCLOAK_CLIENT_ID: ${HORUSEC_KEYCLOAK_CLIENT_ID} # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_KEYCLOAK_CLIENT_SECRET: ${HORUSEC_KEYCLOAK_CLIENT_SECRET} # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_KEYCLOAK_REALM: ${HORUSEC_KEYCLOAK_REALM} # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_LDAP_BASE: "dc=wimpi,dc=net"
      HORUSEC_LDAP_HOST: "ldap-service"
      HORUSEC_LDAP_PORT: "10389"
      HORUSEC_LDAP_USESSL: "false"
      HORUSEC_LDAP_SKIP_TLS: "true"
      HORUSEC_LDAP_INSECURE_SKIP_VERIFY: "true"
      HORUSEC_LDAP_BINDDN: "uid=admin,ou=system"
      HORUSEC_LDAP_BINDPASSWORD: "secret" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_LDAP_USERFILTER: "(sAMAccountName=%s)"
      HORUSEC_LDAP_ADMIN_GROUP: "admin" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_ENABLE_APPLICATION_ADMIN: "false"
      HORUSEC_APPLICATION_ADMIN_DATA: "{\"username\": \"horusec-admin\", \"email\":\"horusec-admin@example.com\", \"password\":\"Devpass0*\"}" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_ENABLE_DEFAULT_USER: "true"
      HORUSEC_DEFAULT_USER_DATA: "{\"username\": \"dev\", \"email\":\"dev@example.com\", \"password\":\"Devpass0*\"}" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_AUTH_TYPE: "horusec"
      HORUSEC_BROKER_HOST: "rabbit"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DISABLE_EMAILS: "true"
  horusec-core:
    image: horuszup/horusec-core:v2.17.2
    ports:
      - "8003:8003"
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
    restart: always
    container_name: horusec-core
    environment:
      HORUSEC_PORT: "8003"
      HORUSEC_DISABLED_BROKER: "true"
      HORUSEC_BROKER_HOST: "rabbit"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@horusec_postgresql:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "false"
      HORUSEC_GRPC_AUTH_URL: "horusec-auth:8007"
  horusec-analytic:
    image: horuszup/horusec-analytic:v2.17.2
    ports:
      - "8005:8005"
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
    restart: always
    container_name: horusec-analytic
    environment:
      HORUSEC_PORT: "8005"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@horusec_postgresql:5432/horusec_analytic_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "false"
      HORUSEC_GRPC_AUTH_URL: "horusec-auth:8007"
      HORUSEC_BROKER_HOST: "rabbit"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
  horusec-api:
    image: horuszup/horusec-api:v2.17.2
    ports:
      - "8000:8000"
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
      - "horusec-auth"
    restart: always
    container_name: horusec-api
    environment:
      HORUSEC_PORT: "8000"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@horusec_postgresql:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "false"
      HORUSEC_GRPC_AUTH_URL: "horusec-auth:8007"
      HORUSEC_BROKER_HOST: "rabbit"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
  horusec-vulnerability:
    image: horuszup/horusec-vulnerability:v2.17.2
    ports:
      - "8001:8001"
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
    restart: always
    container_name: horusec-vulnerability
    environment:
      HORUSEC_PORT: "8001"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@horusec_postgresql:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_DATABASE_SQL_LOG_MODE: "false"
      HORUSEC_GRPC_AUTH_URL: "horusec-auth:8007"
      HORUSEC_BROKER_HOST: "rabbit"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
      HORUSEC_BROKER_PASSWORD: "guest" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
  horusec-webhook:
    image: horuszup/horusec-webhook:v2.17.2
    ports:
      - "8004:8004"
    depends_on:
      - "rabbit"
      - "horusec_postgresql"
    restart: always
    container_name: horusec-webhook
    environment:
     HORUSEC_PORT: "8004"
     HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@horusec_postgresql:5432/horusec_db?sslmode=disable" # Sensitive information we not recommended usage in production environment, change for usage strong data for connection with this service
     HORUSEC_DATABASE_SQL_LOG_MODE: "false"
     HORUSEC_GRPC_AUTH_URL: "horusec-auth:8007"
     HORUSEC_BROKER_HOST: "rabbit"
     HORUSEC_BROKER_PORT: "5672"
     HORUSEC_BROKER_USERNAME: "guest"
     HORUSEC_BROKER_PASSWORD: "guest"
  horusec-manager:
    image: horuszup/horusec-manager:v2.17.2
    ports:
      - "8043:8080"
    restart: always
    container_name: horusec-manager
    environment:
      HORUSEC_ENDPOINT_API: ${HORUSEC_ENDPOINT_API}
      HORUSEC_ENDPOINT_ANALYTIC: ${HORUSEC_ENDPOINT_ANALYTIC}
      HORUSEC_ENDPOINT_CORE: ${HORUSEC_ENDPOINT_CORE}
      HORUSEC_ENDPOINT_WEBHOOK: ${HORUSEC_ENDPOINT_WEBHOOK}
      HORUSEC_ENDPOINT_AUTH: ${HORUSEC_ENDPOINT_AUTH}
      HORUSEC_ENDPOINT_VULNERABILITY: ${HORUSEC_ENDPOINT_VULNERABILITY}
      REACT_APP_HORUSEC_ENDPOINT_API: ${HORUSEC_ENDPOINT_API}
      REACT_APP_HORUSEC_ENDPOINT_ANALYTIC: ${HORUSEC_ENDPOINT_ANALYTIC}
      REACT_APP_HORUSEC_ENDPOINT_CORE: ${HORUSEC_ENDPOINT_CORE}
      REACT_APP_HORUSEC_ENDPOINT_WEBHOOK: ${HORUSEC_ENDPOINT_WEBHOOK}
      REACT_APP_HORUSEC_ENDPOINT_AUTH: ${HORUSEC_ENDPOINT_AUTH}
      REACT_APP_HORUSEC_ENDPOINT_VULNERABILITY: ${HORUSEC_ENDPOINT_VULNERABILITY}
      REACT_APP_KEYCLOAK_BASE_PATH: ${REACT_APP_KEYCLOAK_BASE_PATH}
      REACT_APP_KEYCLOAK_CLIENT_ID: ${REACT_APP_KEYCLOAK_CLIENT_ID}
      REACT_APP_KEYCLOAK_REALM: ${REACT_APP_KEYCLOAK_REALM}
      REACT_APP_MICROFRONTEND_PUBLIC_PATH: ${REACT_APP_MICROFRONTEND_PUBLIC_PATH}
      REACT_APP_HORUSEC_MANAGER_THEME: ${REACT_APP_HORUSEC_MANAGER_THEME}
