{{- if (include "ingress.enabled" .) }}
apiVersion: {{ include "ingress.apiVersion" . }}
kind: Ingress
metadata:
  labels:
    app: horusec-manager
  name: horusec
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.global.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
  {{- with .Values.global.ingress.annotations  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- include "ingress.rules" . | nindent 2 }}
{{- include "ingress.tls" . | nindent 2 }}
{{- end }}