{{- if (include "ingress.enabled" .) }}
apiVersion: {{ include "ingress.apiVersion" . }}
kind: Ingress
metadata:
  labels:
    app: horusec-manager
  name: horusec
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    {{- if .Values.components.analytic.ingress.enabled }}
    - host: {{ .Values.components.analytic.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: analytic
              servicePort: {{ .Values.components.analytic.port.http }}
            path: /analytic
    {{- end }}
    {{- if .Values.components.api.ingress.enabled }}
    - host: {{ .Values.components.api.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: {{ .Values.components.api.port.http }}
            path: /api
    {{- end }}
    {{- if .Values.components.auth.ingress.enabled }}
    - host: {{ .Values.components.auth.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: auth
              servicePort: {{ .Values.components.auth.port.http }}
            path: /auth
    {{- end }}
    {{- if .Values.components.core.ingress.enabled }}
    - host: {{ .Values.components.core.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: core
              servicePort: {{ .Values.components.core.port.http }}
            path: /core
    {{- end }}
    {{- if .Values.components.manager.ingress.enabled }}
    - host: {{ .Values.components.manager.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: manager
              servicePort: {{ .Values.components.manager.port.http }}
    {{- end }}
    {{- if .Values.components.messages.ingress.enabled }}
    - host: {{ .Values.components.messages.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: messages
              servicePort: {{ .Values.components.messages.port.http }}
            path: /messages
    {{- end }}
    {{- if .Values.components.vulnerability.ingress.enabled }}
    - host: {{ .Values.components.vulnerability.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: vulnerability
              servicePort: {{ .Values.components.vulnerability.port.http }}
            path: /vulnerability
    {{- end }}
{{- include "ingress.tls" . | nindent 2 }}
{{- end }}
